package com.hspedu.ch12.Exception;

public class Exception03  {
    public static void main (String[] args) {
       /*
        try{代码
        1.NullPointException
        2.ArithmeticException
        }catch ( NullPointException e){
               e.
        }catch( ArithmeticException e){
               e.
        }//子类异常再前，父类在后
        catch (Exception e){
            捕获异常
            // e.printStackTrace();
        }
        finally {

            不管是否发生异常，都运行
        }
        */

        /*
        try{
        }
        finally{
        }
         */
    }
}
